### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by fzerorubigd** [ph4r5h4d/wait4it#28]
Tags in this repository looks like semantic versioning, but they are not actually. each tag is one major version after the previous tag. Also my suggestion is to use git flow, or something similar from now on, and upgrade the version only if something backward incompatible happens.

**Comment by ph4r5h4d** [comment]
I agree, the versioning was like if a new service is added a new version is released. we can change it.

**Comment by fzerorubigd** [comment]
I guess we already start this, can you please change the default branch into develop?

**Comment by ph4r5h4d** [comment]
Done, shall we close this issue?
