### ISSUE TITLE
Use context library

### ISSUE THREAD

**Issue by fzerorubigd** [ph4r5h4d/wait4it#30]
Some checks can use context for handling timeouts and other things. its better to move to golang context in the interface, for calling Check function.

**Comment by ph4r5h4d** [comment]
If you are talking about HTTP and TCP checks, I think it's possible. But I wonder what you are exactly thinking about the interface changes. Can you provide an example of the changes that happen to the check interface?

**Comment by fzerorubigd** [comment]
Basically anything. so the check should accept a context and pass it to the lower level. the checkers should use it for timeout and call to any api that is support context

**Comment by ph4r5h4d** [comment]
Ahh, I think I get what you are suggesting. 
I agree. Based on your recent changes, I can also work on this issue this weekend.
