### ISSUE TITLE
Check Chain

### ISSUE THREAD

**Issue by ph4r5h4d** [ph4r5h4d/wait4it#46]
Does it make sense, and do you think it's usable to have a chain of checks?

This means the app can do multiple checks instead of one if required. For example, it will first check for MySQL and then wait for some time and then check an HTTP endpoint, and so on...

Will such a feature be any of use?

Also, we need to keep in mind that this feature will make the app a bit more complex.

**Comment by ph4r5h4d** [comment]
Also, this feature can be a separate tool that internally will consume and use wait4it modules.

**Comment by mbrostami** [comment]
My experience, It can be done with bash script as well in more flexible ways. KI(S)S ;)

**Comment by ph4r5h4d** [comment]
I know, but lots of stuff, even wait4it, can be done via bash scripts. I think that is not the case but that for a user of wait4it, is it going to be valuable or not?

**Comment by tiagostutz** [comment]
Maybe another project called `wait4those` that uses `wait4it` as a module or something like could be a catch, so `wait4it` keeps simples and straightforward as it is. 

BTW, nice project! 🚀

**Comment by ph4r5h4d** [comment]
That would be a good idea. BTW, I like the naming wait4those sounds fun :)
I'm gonna close this one then.
