### ISSUE TITLE
MySQL app level check

### ISSUE THREAD

**Issue by mbrostami** [ph4r5h4d/wait4it#48]
Beside the tcp check, it would be great if we can have an application level check. In case of MySQL it can be a simple query like 'select 1;'. Cause it might happen that connection works fine but application not.
It will also be useful for health check in load balancers.

**Comment by ph4r5h4d** [comment]
For now, the check is a Go driver ping check, which means it actually checks the service status being ready to serve requests.
Kindly check and see if further development on this checker is required or not.
