### ISSUE TITLE
Migrate to ghcr.io

### ISSUE THREAD

**Issue by numb95** [ph4r5h4d/wait4it#62]
As a result of the docker hub [rate limit policy](https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates) and also the speed of pulling images from ghcr.io, I recommend just storing (or a copy of it) wait4it on ghcr.io.
Regards,

**Comment by ph4r5h4d** [comment]
After a long time and some considerations, I think I'd rather prefer to work on the OS packages and keep the docker image in docker hub for the moment, I'm going to close the issue.
