### ISSUE TITLE
wait4it-v11.1.4-linux-amd64 binary is mage

### ISSUE THREAD

**Issue by W1M0R** [ph4r5h4d/wait4it#63]
I get the following result after downloading and extracting https://github.com/ph4r5h4d/wait4it/releases/download/v11.1.4/wait4it-v11.1.4-linux-amd64.tar.gz:

```
> ./wait4it
Error determining list of magefiles: failed to list non-mage gofiles: exit status 1: go: cannot find main module, but found .git/config in /home/vagrant/hrs
        to create a module there, run:
        cd .. && go mod init
```

I would expect the `wait4it` binary to behave as documented, but in this case it seems like it is just the `mage` binary.

I get the same result for:

1.  https://github.com/ph4r5h4d/wait4it/releases/download/v11.1.3/wait4it-v11.1.3-linux-amd64.tar.gz
2. https://github.com/ph4r5h4d/wait4it/releases/download/v11.1.2/wait4it-v11.1.2-linux-amd64.tar.gz

**Comment by ph4r5h4d** [comment]
I can see there is an issue, I'll try to fix it in the coming days. probably something is wrong during the automatic build. 
Thanks for reporting it. I'll update the issue once it's fixed.

**Comment by ph4r5h4d** [comment]
Meanwhile, I can suggest using the Docker image or building the app yourself.
Again, thanks for reporting the issue.

**Comment by ph4r5h4d** [comment]
I know it's been a long time but the latest release binaries should be good to go and works as expected.
I'll be issuing more updates in the coming days to the Docker image as well, but for now, it should be good to go.
Kindly reopen the issue if you are still experiencing errors.
