### ISSUE TITLE
Update dependency "github.com/fzerorubigd/clictx"

### ISSUE THREAD

**Issue by Ben131-Go** [ph4r5h4d/wait4it#92]
## Background
Repo `github.com/ph4r5h4d/wait4it` depends on `github.com/fzerorubigd/clictx@v1.1.0`.<br>
<https://github.com/ph4r5h4d/wait4it/blob/main/go.mod#L9><br>
However, comparing version `v1.1.0` of `github.com/fzerorubigd/clictx` from proxy.golang.org and github, there are inconsistencies.<br>
> [commit time of the copy on github.com](https://api.github.com/repos/fzerorubigd/clictx/commits/3818b21)
```txt
"committer": {
      "name": "fzerorubigd",
      "email": "fzerorubigd@gmail.com",
      "date": "2020-12-26T01:52:31Z"
    }
```
> [commit time of the copy on proxy.golang.org](https://proxy.golang.org/github.com/fzerorubigd/clictx/@v/v1.1.0.info)
```txt
{"Version":"v1.1.0","Time":"2020-12-26T01:33:07Z"}
```
So the checksum from the code in github does not match the checksum saved in sum.golang.org. The `v1.1.0` tag of `github.com/fzerorubigd/clictx` might have been retagged after a minor edition on github. I guess you use proxy.golang.org to get dependencies, but that also shows that your project is depending on the copy of `github.com/fzerorubigd/clictx@v1.1.0` before its edition. Depending upon such inconsistent tag version may also result in some unexpected errors as well as build errors due to different proxy settings.<br>
For example, when someone who does not use proxy.golang.org, say `GOPROXY=direct`, attempts to get `github.com/fzerorubigd/clictx@v1.1.0`, the following error occurs.
```Go
go: downloading github.com/fzerorubigd/clictx v1.1.0
go: github.com/fzerorubigd/clictx@v1.1.0: verifying module: checksum mismatch
        downloaded: h1:BaZOGM6+gOrZ8/PrYONXuOGpLoIB7D3SUK4D3S8wbGo=
        sum.golang.org: h1:xWQ8Plr9HV+gUB0VP8FRswGfrjDlJXmjD0aw3sNbGos=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```
So, this is a reminder in the hope that you can get rid of this unreliable version of project `github.com/fzerorubigd/clictx`.
### 1. Bump the version of dependency `github.com/fzerorubigd/clictx`
It seems that `github.com/fzerorubigd/clictx` is no longer maintained since there is [standard library](https://pkg.go.dev/os/signal#NotifyContext) for doing this.

## References
+ <https://proxy.golang.org/>

**Comment by ph4r5h4d** [comment]
Hi, I'm planning to remove the dependency on the next release.
It's been a long time since I've released the app and in my free time, I was mostly working on the tests, so it's easier to contribute to the project.
Thanks for noticing the issue.

**Comment by ph4r5h4d** [comment]
I've switched back to standard go context, tests seem fine, I need to do a more thorough testing to make sure the app will not face any issues.
I'll close the issue once I'm confident everything is good and will make a release afterward.
